// ==========================================
// TOKENS Y ESTILOS VISUALES DEL LOGIN
// ==========================================
export const loginStyles = {
  container: {
    display: 'flex',
    width: '100vw',
    height: '100vh',
    margin: 0,
    padding: 0,
    overflow: 'hidden',
    backgroundColor: '#0B1120',
    fontFamily: 'Inter, system-ui, sans-serif',
    color: '#F8FAFC',
    boxSizing: 'border-box' as const,
  },
  leftPanel: {
    flex: '1.2',
    background: 'radial-gradient(circle at top left, #1E293B 0%, #0F172A 70%)',
    display: 'flex',
    flexDirection: 'column' as const,
    justifyContent: 'space-between',
    padding: '60px',
    borderRight: '1px solid rgba(51, 65, 85, 0.4)',
    position: 'relative' as const,
    overflow: 'hidden',
  },
  glowOrb1: {
    position: 'absolute' as const,
    top: '-10%',
    left: '-10%',
    width: '450px',
    height: '450px',
    background: 'radial-gradient(circle, rgba(37, 99, 235, 0.18) 0%, rgba(15, 23, 42, 0) 70%)',
    borderRadius: '50%',
    zIndex: 1,
    pointerEvents: 'none' as const,
  },
  glowOrb2: {
    position: 'absolute' as const,
    bottom: '-15%',
    right: '-10%',
    width: '400px',
    height: '400px',
    background: 'radial-gradient(circle, rgba(56, 189, 248, 0.1) 0%, rgba(15, 23, 42, 0) 70%)',
    borderRadius: '50%',
    zIndex: 1,
    pointerEvents: 'none' as const,
  },
  rightPanel: {
    flex: '1',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '40px',
    backgroundColor: '#0F172A',
    position: 'relative' as const,
  },
  card: {
    width: '100%',
    maxWidth: '420px',
    backgroundColor: 'rgba(30, 41, 59, 0.6)',
    backdropFilter: 'blur(16px)',
    border: '1px solid rgba(51, 65, 85, 0.6)',
    borderRadius: '24px',
    padding: '40px',
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.5)',
  },
  inputBox: {
    width: '100%',
    padding: '15px 16px 15px 48px',
    backgroundColor: 'rgba(15, 23, 42, 0.7)',
    border: '1px solid #334155',
    borderRadius: '12px',
    color: '#F8FAFC',
    fontSize: '15px',
    outline: 'none',
    boxSizing: 'border-box' as const,
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
  },
  featureBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '14px 18px',
    backgroundColor: 'rgba(30, 41, 59, 0.5)',
    border: '1px solid rgba(51, 65, 85, 0.8)',
    borderRadius: '14px',
    color: '#E2E8F0',
    fontSize: '14px',
    fontWeight: '500',
    backdropFilter: 'blur(8px)',
  },
};
