import { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  container: {
    padding: '24px',
    color: '#F8FAFC',
    minHeight: '100vh',
    backgroundColor: '#0F172A',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '24px',
  },
  title: {
    fontSize: '24px',
    fontWeight: '700',
    color: '#F8FAFC',
    margin: 0,
  },
  subtitle: {
    fontSize: '14px',
    color: '#94A3B8',
    marginTop: '4px',
  },
  btnNuevaOT: {
    backgroundColor: '#2563EB',
    color: '#FFFFFF',
    border: 'none',
    padding: '10px 18px',
    borderRadius: '8px',
    fontWeight: '600',
    fontSize: '14px',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
  },
  tableroGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '20px',
    marginBottom: '32px',
  },
  columnaZanja: {
    backgroundColor: '#1E293B',
    borderRadius: '12px',
    padding: '20px',
    border: '1px solid #334155',
  },
  tituloZanja: {
    fontSize: '18px',
    fontWeight: '600',
    color: '#38BDF8',
    marginBottom: '16px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  tarjetaVacia: {
    padding: '32px 16px',
    border: '2px dashed #334155',
    borderRadius: '8px',
    textAlign: 'center',
    color: '#64748B',
  },
  tarjetaOt: {
    backgroundColor: '#0F172A',
    borderRadius: '8px',
    padding: '16px',
    border: '1px solid #334155',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
  },
  badgeEstado: {
    padding: '4px 10px',
    borderRadius: '12px',
    fontSize: '12px',
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  historicoContainer: {
    backgroundColor: '#1E293B',
    borderRadius: '12px',
    padding: '20px',
    border: '1px solid #334155',
  },
  tabla: {
    width: '100%',
    borderCollapse: 'collapse',
    marginTop: '12px',
  },
  th: {
    textAlign: 'left',
    padding: '12px',
    borderBottom: '1px solid #334155',
    color: '#94A3B8',
    fontSize: '13px',
  },
  td: {
    padding: '12px',
    borderBottom: '1px solid #334155',
    color: '#E2E8F0',
    fontSize: '14px',
  },
};
